### PR TITLE
Fix/ui button

### LINKED ISSUE #189: FIX/UI - Styled Components Button
## The story:
As a **developer**, I want to **implement styled components for our buttons**

---

## What we should do:
We should **implement styled components** so that **we can have styled component buttons**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [x] Migrate from Tailwind to styled component in the Button Component

### PR DESCRIPTION
**Pull request by f-westergren**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Fixed issues (PRs without this will not be accepted)
- Fixes #189 

## Changes
- Migrates to styled components from tailwind

## PR Checklist
- [x] Does your PR contain relevant tests that pass?
- [x] Is your code linted? `yarn lint` or `yarn lint:fix`
- [x] Does your code build correctly in ALL projects? `yarn build`

### CODE REVIEW

File: packages/ui/components/Button/Button.tsx [hunk 1]
```diff
@@ -1,31 +1,110 @@
...
+const StyledButton = styled.button<ButtonProps>`
+  display: inline-block;
+  font-weight: 800;
+  height: 2.25rem;
+  line-height: 2.25rem;
+  padding-left: 0.75rem;
+  padding-right: 0.75rem;
+  border-radius: 0.5rem;
+  letter-spacing: 0.05em;
+  font-size: 0.875rem;
```
Comment (tristanMatthias) [inline packages/ui/components/Button/Button.tsx]: Can we standardize these somehow? Also, what base are we using? Should be 10, not 16

**Review by quimgv — APPROVED** [review]
Looks good @f-westergren !! Awesome work thanks!
